<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>OmniX.API</RootNamespace>
    <AssemblyName>OmniX.API</AssemblyName>
    <UserSecretsId>omnix-api-secrets</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"  Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design"           Version="8.0.8" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks"  Version="8.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore"                         Version="6.7.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations"             Version="6.7.3" />
    <PackageReference Include="Serilog.AspNetCore"                             Version="8.0.2" />
    <PackageReference Include="Serilog.Enrichers.Environment"                  Version="2.3.0" />
    <PackageReference Include="Serilog.Enrichers.Thread"                       Version="4.0.0" />
    <PackageReference Include="Serilog.Sinks.Console"                          Version="5.0.1" />
    <PackageReference Include="Serilog.Sinks.File"                             Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../OmniX.Application/OmniX.Application.csproj" />
    <ProjectReference Include="../OmniX.Infrastructure/OmniX.Infrastructure.csproj" />
  </ItemGroup>
</Project>
